version: '3.9'

services:
  postgres-db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${PDB_USER}
      - POSTGRES_PASSWORD=${PDB_PASSWORD}
      - POSTGRES_DB=${PDB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - testuzb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PDB_USER} -d ${PDB_NAME} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    networks:
      - testuzb
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres-db
    command: ["-path", "/migrations", "-database" ,"postgres://${PDB_USER}:${PDB_PASSWORD}@postgres:${PDB_PORT}/${PDB_NAME}?sslmode=disable","up"]

  checkerservice:
    container_name: checkerservice
    build: .
    ports:
      - "50054:50054"
    networks:
      - testuzb
    depends_on:
      postgres-db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "grpc_health_probe -addr=:50054"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  testuzb:
    external: true

volumes:
  db:
    driver: local

